version: "3.1"
services:
  db:
    image: postgres
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret

  api:
    build: .
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - db
    environment:
      DB_HOST: db
networks:
  backend:
